{% set version = "2025.5" %}

package:
  name: shaderc
  version: {{ version }}

source:
  url: https://github.com/google/shaderc/archive/v{{ version }}.tar.gz
  sha256: fca5041b1fdea6daba167b63e04e55e5059fab40828342126169336643445447
  patches:
    - patches/0001-Update-build-version-generation.patch
    - patches/0002-Update-the-location-of-SPRV-headers.patch
    - patches/0003-Update-thirdparty-dependency-resolution.patch
    - patches/0004-Update-dependenices-on-glslang.patch
    - patches/0005-Only-install-shared-libraries.patch

build:
  number: 1
  run_exports:
    # This is kinda annoying, the SO version is not related to the version
    - {{ pin_subpackage('shaderc', max_pin='x.x') }}

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make                                   # [unix]
  host:
    - spirv-tools
    - spirv-headers
    - glslang

test:
  commands:
    - test -f ${PREFIX}/lib/libshaderc${SHLIB_EXT}                # [unix]
    - if not exist %PREFIX%\\Library\\bin\\shaderc.dll exit 1     # [win]
    - if not exist %PREFIX%\\Library\\lib\\shaderc.lib exit 1     # [win]
    - glslc --help

about:
  home: https://github.com/google/shaderc
  summary: A collection of tools, libraries and tests for shader compilation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
