{% set version = "2025.1" %}

package:
  name: shaderc
  version: {{ version }}

source:
  url: https://github.com/google/shaderc/archive/v{{ version }}.tar.gz
  sha256: 358f9fa87b503bc7a3efe1575fbf581fca7f16dbc6d502ea2b02628d2d0d4014
  patches:
    - patches/0001-Update-build-version-generation.patch
    - patches/0002-Update-the-location-of-SPRV-headers.patch
    - patches/0003-Update-thirdparty-dependency-resolution.patch
    - patches/0004-Update-dependenices-on-glslang.patch
    - patches/0005-Only-install-shared-libraries.patch

build:
  number: 0
  run_exports:
    # This is kinda annoying, the SO version is not related to the version
    - {{ pin_subpackage('shaderc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                                   # [unix]
  host:
    - spirv-tools 2025.1
    - spirv-headers
    - glslang

test:
  commands:
    - test -f ${PREFIX}/lib/libshaderc${SHLIB_EXT}                # [unix]
    - if not exist %PREFIX%\\Library\\bin\\shaderc.dll exit 1     # [win]
    - if not exist %PREFIX%\\Library\\lib\\shaderc.lib exit 1     # [win]
    - glslc --help

about:
  home: https://github.com/google/shaderc
  summary: A collection of tools, libraries and tests for shader compilation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
